### ISSUE TITLE
Can't find dependency installation information.

### ISSUE THREAD

**Issue by karsmalla** [JakeFurtaw/Chat-RAG#11]
I am trying to install the dependencies and I am stuck with

  File "/Chat-RAG/app.py", line 2, in <module>
    from chatrag import demo
  File "/Chat-RAG/chatrag.py", line 3, in <module>
    from gradio_utils import GradioUtils
  File "/Chat-RAG/gradio_utils.py", line 3, in <module>
    from model_utils import ModelManager, ModelParamUpdates
  File "/Chat-RAG/model_utils.py", line 3, in <module>
    from chat_utils import create_chat_engine
  File "/Chat-RAG/chat_utils.py", line 3, in <module>
    from llama_index.vector_stores.neo4jvector import Neo4jVectorStore

**Comment by JakeFurtaw** [comment]
Some of these may not be necessary because I use this environment for many of my AI Assistant projects. But here is the full list of dependencies fro you!


Package                                  Version
---------------------------------------- ------------
accelerate                               0.33.0
aiofiles                                 23.2.1
aiohappyeyeballs                         2.4.0
aiohttp                                  3.10.5
aiosignal                                1.3.1
annotated-types                          0.7.0
anthropic                                0.28.1
anyio                                    4.4.0
asgiref                                  3.8.1
attrs                                    24.2.0
backoff                                  2.2.1
bcrypt                                   4.2.0
beautifulsoup4                           4.12.3
bitsandbytes                             0.43.3
build                                    1.2.1
cachetools                               5.5.0
certifi                                  2024.8.30
charset-normalizer                       3.3.2
chroma-hnswlib                           0.7.6
chromadb                                 0.5.5
click                                    8.1.7
coloredlogs                              15.0.1
contourpy                                1.3.0
cycler                                   0.12.1
dataclasses-json                         0.6.7
Deprecated                               1.2.14
dirtyjson                                1.0.8
distro                                   1.9.0
einops                                   0.8.0
environs                                 9.5.0
fastapi                                  0.112.2
ffmpy                                    0.4.0
filelock                                 3.15.4
flash-attn                               2.6.3
flatbuffers                              24.3.25
fonttools                                4.53.1
frozenlist                               1.4.1
fsspec                                   2024.6.1
google-auth                              2.34.0
googleapis-common-protos                 1.65.0
gradio                                   4.42.0
gradio_client                            1.3.0
greenlet                                 3.0.3
grpcio                                   1.66.1
h11                                      0.14.0
httpcore                                 1.0.5
httptools                                0.6.1
httpx                                    0.27.2
huggingface-hub                          0.24.6
humanfriendly                            10.0
idna                                     3.8
importlib_metadata                       8.4.0
importlib_resources                      6.4.4
Jinja2                                   3.1.4
jiter                                    0.5.0
joblib                                   1.4.2
jsonpatch                                1.33
jsonpointer                              3.0.0
kiwisolver                               1.4.5
kubernetes                               30.1.0
langchain                                0.2.16
langchain-community                      0.2.16
langchain-core                           0.2.38
langchain-huggingface                    0.0.3
langchain-ollama                         0.1.3
langchain-text-splitters                 0.2.4
langsmith                                0.1.117
llama-cloud                              0.0.15
llama-index                              0.11.2
llama-index-agent-openai                 0.3.0
llama-index-cli                          0.3.0
llama-index-core                         0.11.3
llama-index-embeddings-huggingface       0.3.1
llama-index-embeddings-openai            0.2.3
llama-index-indices-managed-llama-cloud  0.3.0
llama-index-legacy                       0.9.48.post3
llama-index-llms-anthropic               0.3.0
llama-index-llms-huggingface             0.3.1
llama-index-llms-nvidia                  0.2.1
llama-index-llms-ollama                  0.3.0
llama-index-llms-openai                  0.2.0
llama-index-llms-openai-like             0.2.0
llama-index-multi-modal-llms-openai      0.2.0
llama-index-program-openai               0.2.0
llama-index-question-gen-openai          0.2.0
llama-index-readers-file                 0.2.0
llama-index-readers-github               0.2.0
llama-index-readers-llama-parse          0.2.0
llama-index-vector-stores-chroma         0.2.0
llama-index-vector-stores-milvus         0.2.3
llama-index-vector-stores-neo4jvector    0.2.1
llama-parse                              0.5.1
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.22.0
matplotlib                               3.9.2
mdurl                                    0.1.2
milvus-lite                              2.4.10
minijinja                                2.2.0
mmh3                                     4.1.0
monotonic                                1.6
mpmath                                   1.3.0
multidict                                6.0.5
mypy-extensions                          1.0.0
neo4j                                    5.24.0
nest-asyncio                             1.6.0
networkx                                 3.3
nltk                                     3.9.1
numpy                                    1.26.4
nvidia-cublas-cu12                       12.1.3.1
nvidia-cuda-cupti-cu12                   12.1.105
nvidia-cuda-nvrtc-cu12                   12.1.105
nvidia-cuda-runtime-cu12                 12.1.105
nvidia-cudnn-cu12                        9.1.0.70
nvidia-cufft-cu12                        11.0.2.54
nvidia-curand-cu12                       10.3.2.106
nvidia-cusolver-cu12                     11.4.5.107
nvidia-cusparse-cu12                     12.1.0.106
nvidia-nccl-cu12                         2.20.5
nvidia-nvjitlink-cu12                    12.6.68
nvidia-nvtx-cu12                         12.1.105
oauthlib                                 3.2.2
ollama                                   0.3.2
onnxruntime                              1.19.0
openai                                   1.43.0
opentelemetry-api                        1.27.0
opentelemetry-exporter-otlp-proto-common 1.27.0
opentelemetry-exporter-otlp-proto-grpc   1.27.0
opentelemetry-instrumentation            0.48b0
opentelemetry-instrumentation-asgi       0.48b0
opentelemetry-instrumentation-fastapi    0.48b0
opentelemetry-proto                      1.27.0
opentelemetry-sdk                        1.27.0
opentelemetry-semantic-conventions       0.48b0
opentelemetry-util-http                  0.48b0
orjson                                   3.10.7
overrides                                7.7.0
packaging                                24.1
pandas                                   2.2.2
pillow                                   10.4.0
pip                                      24.2
posthog                                  3.6.0
protobuf                                 5.28.0
psutil                                   6.0.0
pyasn1                                   0.6.0
pyasn1_modules                           0.4.0
pydantic                                 2.8.2
pydantic_core                            2.20.1
pydub                                    0.25.1
Pygments                                 2.18.0
pymilvus                                 2.4.6
pyparsing                                3.1.4
pypdf                                    4.3.1
PyPika                                   0.48.9
pyproject_hooks                          1.1.0
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
python-multipart                         0.0.9
pytz                                     2024.1
PyYAML                                   6.0.2
regex                                    2024.7.24
requests                                 2.32.3
requests-oauthlib                        2.0.0
rich                                     13.8.0
rsa                                      4.9
ruff                                     0.6.3
safetensors                              0.4.4
scikit-learn                             1.5.1
scipy                                    1.14.1
semantic-version                         2.10.0
sentence-transformers                    3.0.1
sentencepiece                            0.2.0
setuptools                               74.0.0
shellingham                              1.5.4
six                                      1.16.0
sniffio                                  1.3.1
soupsieve                                2.6
SQLAlchemy                               2.0.32
starlette                                0.38.2
striprtf                                 0.0.26
sympy                                    1.13.2
tenacity                                 8.5.0
text-generation                          0.7.0
threadpoolctl                            3.5.0
tiktoken                                 0.7.0
tokenizers                               0.19.1
tomlkit                                  0.12.0
torch                                    2.4.0
torchaudio                               2.4.0
torchvision                              0.19.0
tqdm                                     4.66.5
transformers                             4.44.2
triton                                   3.0.0
typer                                    0.12.5
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2024.1
ujson                                    5.10.0
urllib3                                  2.2.2
uvicorn                                  0.30.6
uvloop                                   0.20.0
watchfiles                               0.24.0
websocket-client                         1.8.0
websockets                               12.0
wheel                                    0.44.0
wrapt                                    1.16.0
xformers                                 0.0.27.post2
yarl                                     1.9.4
zipp                                     3.20.1
